using UnityEngine;

public class CoinScript : MonoBehaviour
{
    public int coinValue = 1;    // âž¤ DEFAULT VALUE (Bronze = 1)

    private void OnTriggerEnter2D(Collider2D collision)
    {
        Debug.Log("Line 7");
        if (collision.CompareTag("Player"))
        {
            Debug.Log("Line 11");
            PlayerController player = collision.GetComponent<PlayerController>();

            if (player != null)
            {
                player.coins += coinValue;   // âž¤ ADD CORRECT VALUE
            }

            // ðŸ”Š Step 19: Play coin sound
            if (SoundManager.Instance != null)
                SoundManager.Instance.PlaySFX("COIN", 0.4f);

            Destroy(gameObject);
        }
    }
}
